# Dockerfile.frontend
FROM python:3.10-slim

WORKDIR /app

# Copy dependencies
COPY frontend/requirements.txt .

# INCREASED TIMEOUT HERE TO AVOID TIMEOUT ISSUES DURING INSTALLATION
RUN pip install --default-timeout=1000 --no-cache-dir -r requirements.txt

# Copy the frontend code
COPY frontend/ ./frontend/

# Expose the Streamlit port
EXPOSE 8501

# Run the Streamlit app
CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]